# Generated by Django 5.1.5 on 2025-02-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
    ]
