# Generated by Django 5.1.5 on 2025-02-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App1', '0002_rename_age_user_age_rename_email_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
