# Generated by Django 5.1.5 on 2025-02-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App1', '0003_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
